language: php

notifications:
  email: false

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3

env:
  global:
    - TEST_PHP_ARGS="-q"
    - REPORT_EXIT_STATUS=1

before_script:
  - cd extension
  - phpize

script: ./configure && NO_INTERACTION=1 REPORT_EXIT_TATUS=1 TEST_PHP_DETAILED=1 make test
