language: php

notifications:
  email: false

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3

env:
  global:
    - TEST_PHP_ARGS="-q"
    - NO_INTERACTION=1

before_script:
  - phpize
  - ./configure 

script: make test

after_failure: "cat tests/*.diff"
